[package]
name = "vector_math"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
auto_ops = "0.3.0"
itertools = "0.10.3"
vector_macro = { path = "../vector_macro" }