[package]
name = "quickmaths"
version = "0.1.0"
edition = "2021"

[dependencies]
vector_math = { path = "vector_math" }
image_buffer = { path = "image_buffer" }
packed_struct = "0.10.0"
rand = "0.8.5"
